name: Flutter CI

# Jab bhi main branch pe push ho, tab yeh workflow chalega
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Code uthao
      - name: Code uthao
        uses: actions/checkout@v3

      # Flutter lagao
      - name: Flutter lagao
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.41.1'

      # Package lao
      - name: Package lao
        run: flutter pub get

      # Test chalao
      - name: Test chalao
        run: flutter test

      # APK banao
      - name: APK banao
        run: flutter build apk --release

      # APK upload karo
      - name: APK upload karo
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk